name: Build Stack64 Windows Client

on:
  workflow_dispatch:

jobs:
  windows:
    name: Build Windows client
    runs-on: windows-2019
    timeout-minutes: 120

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: x86-windows-static
          vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          vcpkgArguments: >
            boost-iostreams boost-asio boost-beast boost-system boost-variant
            boost-lockfree boost-process boost-program-options boost-uuid
            boost-filesystem luajit glew physfs openal-soft libogg libvorbis
            zlib libzip bzip2 openssl liblzma

      - name: Integrate vcpkg
        run: |
          ${{ runner.workspace }}\vcpkg\vcpkg integrate install

      - name: Build DirectX client
        working-directory: vc16
        run: |
          MSBuild otclient.sln /property:Configuration=DirectX /p:BUILD_REVISION=${{ github.run_number }}

      - name: Build OpenGL client
        working-directory: vc16
        run: |
          MSBuild otclient.sln /property:Configuration=OpenGL /p:BUILD_REVISION=${{ github.run_number }}

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: OTCv8-Stack64-Windows
          path: |
            otclient_dx.exe
            otclient_gl.exe
            *.dll
          if-no-files-found: error
